spring.application.name=order-service

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/ordereasy_order_db
spring.datasource.username=spring_user
spring.datasource.password=Spring@2024

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Port
server.port=8083