spring.application.name=auth-service

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/ordereasy_auth_db
spring.datasource.username=spring_user
spring.datasource.password=Spring@2024

# JPA (VERY IMPORTANT ?)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8081

# JWT
jwt.secret=mysecretkeymysecretkeymysecretkeymysecretkeymysecretkey

# Twilio OTP
twilio.account-sid=AC57a8c43b999b3f6a37d4e298dc95282f
twilio.auth-token=caad9b2a984b718bcafab5a84d590988
twilio.verify-service-sid=VAded395b1493426a38e0e06fcda9335c8