spring.application.name=auth-service

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/ordereasy_auth_db
spring.datasource.username=spring_user
spring.datasource.password=Spring@2024

# JPA (VERY IMPORTANT ?)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8081