# Application
spring.application.name=api-gateway

# Server
server.port=8084

# ================= ROUTES =================

# Auth Service
spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**

# Order Service
spring.cloud.gateway.server.webflux.routes[1].id=order-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8083
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/orders/**

# Inventory Service (Products)
spring.cloud.gateway.server.webflux.routes[2].id=inventory-service
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8086
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/products/**

# Inventory Service (Stock)
spring.cloud.gateway.server.webflux.routes[3].id=inventory-service-stock
spring.cloud.gateway.server.webflux.routes[3].uri=http://localhost:8086
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/stock/**

# Tracking Service
spring.cloud.gateway.server.webflux.routes[4].id=tracking-service
spring.cloud.gateway.server.webflux.routes[4].uri=http://localhost:8088
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/tracking/**

# Delivery Service
spring.cloud.gateway.server.webflux.routes[5].id=delivery-service
spring.cloud.gateway.server.webflux.routes[5].uri=http://localhost:8087
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/deliveries/**

# ? Notification Service (NEW)
spring.cloud.gateway.server.webflux.routes[6].id=notification-service
spring.cloud.gateway.server.webflux.routes[6].uri=http://localhost:8089
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/notifications/**

# ================= JWT =================
jwt.secret=mysecretkeymysecretkeymysecretkeymysecretkeymysecretkey