spring.application.name=api-gateway

server.port=8084

spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.server.webflux.routes[1].id=order-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8083
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/orders/**

# JWT
jwt.secret=mysecretkeymysecretkeymysecretkeymysecretkeymysecretkey